version: 2
jobs:
 build:
   docker:
    - image: docker:18.05.0-ce-git
   steps:
     - checkout
     - setup_remote_docker:
         docker_layer_caching: true
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: docker build --squash -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest .
     - run: docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
     - run: docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
